project:
  type: website

website:
  title: "Geographic Analysis - Group 6 AD688"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_analysis.qmd
        text: Data Analysis
      - href: research.qmd
        text: Research
      - href: careers.qmd
        text: Career Strategy
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



