project:
  type: website

website:
  title: "Geographic Analysis - Group 6 AD688"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_analysis.qmd
        text: Data Analysis
      - href: ml_methods.qmd
        text: ML Methods
      - href: gap_analysis.qmd
        text: Skills Gap Analysis
execute:
  echo: true
  cache: true
  freeze: auto
  kernal: python3
  keep-session: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



